### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by MrAmazing137** [overfl0/Bulletproof-Arma-Launcher#179]
An error occured: Libtorrent error: The process cannot access the file because it is being used by another process: D:\SteamLibrary\steamapps\common\Arma 3\Frontline\@RHSAFRF\addons\rhs_weapons2.pbo

**Comment by overfl0** [comment]
Hi!

Did this issue happen ever after?
Would it be possible that an AV was reading that file at that very moment and thus was the reason for that message?

**Comment by overfl0** [comment]
Bump! Hey! I need an answer from you if you want me to be able to investigate the issue.

**Comment by overfl0** [comment]
If the issue occurs again, please reopen this ticket.
