### ISSUE TITLE
Help "LauncherName_autoupdate"

### ISSUE THREAD

**Issue by cshard447** [overfl0/Bulletproof-Arma-Launcher#201]
please tell me and where should be folder  LauncherName_autoupdate

Thanks!

**Comment by overfl0** [comment]
I've added this to the Wiki, today:
https://github.com/overfl0/Bulletproof-Arma-Launcher/wiki/Mod-management#creating-a-new-metadatajson

Also see the part about updating

**Comment by cshard447** [comment]
Thanks!
