### ISSUE TITLE
Launcher does not start (.kivy log)

### ISSUE THREAD

**Issue by cshard447** [overfl0/Bulletproof-Arma-Launcher#202]
Hi!
help please, when I run the launcher, it immediately closes

OC: Windows 8.1

.kivy log

[INFO   ] Logger: Record log in C:\Users\Anton\.kivy\logs\kivy_17-02-23_21.txt
[INFO   ] Kivy: v1.9.2-dev0
[INFO   ] Python: v2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
[WARNING] Settings: Launcher config could not be loaded
[INFO   ] Settings: loaded args: {u'basedir_change_notice': 0, u'mod_data_cache': None, u'use_exception_popup': False, u'update': False, u'seeding_type': u'while_not_playing', u'launcher_moddir': None, u'max_upload_speed': 0, u'max_download_speed': 0, u'selected_server': False, u'launcher_basedir': None}
[INFO   ] Factory: 193 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Video: Provider: null(['video_ffmpeg', 'video_ffpyplayer'] ignored)
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <4.2.0 - Build 10.18.10.3308>
[INFO   ] GL: OpenGL vendor <Intel>
[INFO   ] GL: OpenGL renderer <Intel(R) HD Graphics 4600>
[INFO   ] GL: OpenGL parsed version: 4, 2
[INFO   ] GL: Shading version <4.20 - Build 10.18.10.3308>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[WARNING] Image: Unable to load image <C:\Users\3EC2~1\AppData\Local\Temp\_MEI77~1\kivy_install\data\glsl\default.png>
[CRITICAL] Window: Unable to find any valuable Window provider.
sdl2 - Exception: SDL2: Unable to load image
  File "site-packages\kivy\core\__init__.py", line 67, in core_select_lib
  File "site-packages\kivy\core\window\window_sdl2.py", line 139, in __init__
  File "site-packages\kivy\core\window\__init__.py", line 841, in __init__
  File "site-packages\kivy\core\window\window_sdl2.py", line 284, in create_window
  File "site-packages\kivy\core\window\__init__.py", line 993, in create_window
  File "kivy\graphics\instructions.pyx", line 758, in kivy.graphics.instructions.RenderContext.__init__ (c:\users\ieuser\appdata\local\temp\pip-1ips61-build\kivy\graphics\instructions.c:12580)
  File "site-packages\kivy\core\image\__init__.py", line 538, in __init__
  File "site-packages\kivy\core\image\__init__.py", line 734, in _set_filename
  File "site-packages\kivy\core\image\__init__.py", line 435, in load
  File "site-packages\kivy\core\image\__init__.py", line 201, in __init__
  File "site-packages\kivy\core\image\img_sdl2.py", line 41, in load

[CRITICAL] App: Unable to get a Window, abort.

**Comment by overfl0** [comment]
Hi,

Are you running the launcher on a computer that is able to run Arma?

Kivy (unfortunately) uses OpenGL and cannot be run on computers that don't support that.
So far, it was impossible to run the launcher either on a remote Windows Server instance and on a Windows 8 Virtual Machine (oddly enough, Windows 7 in the same Virtual Box runs fine). Neither of those machines can be used to run Arma.

Anyway, this is a Kivy/SDL2 issue and, as you can see in the stacktrace, the launcher code is not even yet started, so you may try your luck in the kivy github or its mailing list.

Alternatively, it should be possible to recompile kivy to use software rendering (by using the MesaGL library, I think) but I tried to do that and was not able to succeed. This may require contact with Kivy developers too (and I'm interested in making it work this way btw.)

**Comment by overfl0** [comment]
Hey! I finally got a MesaGL dll to work but I haven't yet had the possibility to test it.

Download this dll and put it in the same directory as the exe: https://ci.appveyor.com/api/buildjobs/9pgy6rserx7yx2gu/artifacts/build%2Fwindows-x86-debug%2Fgallium%2Ftargets%2Flibgl-gdi%2Fopengl32.dll

Alternatively, if you're using Remote Desktop for connecting to that computer, try using VNC instead of RDP as I've read that RDP makes some funny things with OpenGL when you're trying to run some executables.
Please tell me if these two solutions have fixed your problem or not.
