### ISSUE TITLE
Kivy designer

### ISSUE THREAD

**Issue by cshard447** [overfl0/Bulletproof-Arma-Launcher#203]
Hi
can be used kivy designer in the launcher?

**Comment by overfl0** [comment]
Hello,

I haven't tried using it but I have doubts whether it will fully work.
You would have to try it yourself and will probably have to "include" the .kv files manually by pasting them into the editor.

You're probably better off working on a small .kv snippet (without any dependencies) in the editor and then copying the modified version to the original .kv file.

**Comment by overfl0** [comment]
By the way, I would **love** to port all the launcher to PyQT and be able to make use of a fully mature and portablre graphics library but this is too much work at this time, unfortunately :(.
