### ISSUE TITLE
Change the color of the Install button when syncing

### ISSUE THREAD

**Issue by Leondor777** [overfl0/Bulletproof-Arma-Launcher#206]
Change the color of the Install/Update/Play button when syncing to 302f36

**Comment by overfl0** [comment]
I tried these values and I'm afraid it's impossible to tell the difference between an enabled and a disabled button with that color set.

I could set it but I'm not really sure it's a good idea, TBH. Also, I realize this is going to be tricky, as the server button's fonts are quite thin and they may quickly become unreadable if I make the text lighter (both buttons share the same color set).

**Comment by overfl0** [comment]
Any idea for a better color? If you want, I can also guess another one that looks fine to me.

**Comment by overfl0** [comment]
I've changed the color to what you've given me but made it semi-transparent. (0x80).
