### ISSUE TITLE
Allow torrent downloads on servers without Steam

### ISSUE THREAD

**Issue by Dr-Eyeball** [overfl0/Bulletproof-Arma-Launcher#207]
We have had server admins trying to use the Launcher on servers which do not run **Steam**, but do use bitTorrents and **steamcmd**.

It seems the launcher will not operate on a computer without Steam installed.

It seems reasonable that a server admin may want to use the launcher ("downloader") to download the mods via bitTorrent, without wanting to launch the game, therefore not requiring Steam to be installed.

**Comment by overfl0** [comment]
I will take a look at that but there is a more concerning problem that will probably be much more complicated to solve than the simple use of steamcmd:

Kivy only works on computers with OpenGL >= 2.0.

What this means is that it won't probably work on remote Windows 2012 Server and the likes by complaining that it could not find Kivy there. It should be possible to work this around by compiling Kivy with MesaGL - a software replacement for OpenGL (slower but we don't care in this case). Unfortunately, I've been unable to do it the last time I tried.

**Comment by overfl0** [comment]
Actually, @Dr-Eyeball I just realized that you can already skip the Steam check for the launcher:

1. Grab the devmode.conf file from here: https://github.com/overfl0/Bulletproof-Arma-Launcher/blob/next/devmode_sample.conf
2. Rename the file to `devmode.conf` and put it in the same directory as the exe
3. Set a fake `steam_executable` value (don't forget to "uncomment" it)

After that, the launcher should work without the need for Steam on the server.
Tell me if that fixed the problem for you.
