### ISSUE TITLE
Use the new (color corrected) BusyIndicator gif

### ISSUE THREAD

**Issue by Leondor777** [overfl0/Bulletproof-Arma-Launcher#211]
![busyindicator_02](https://cloud.githubusercontent.com/assets/26221065/24019606/5aff0192-0aa1-11e7-9acb-7bc199ef0e1b.gif)
https://mega.nz/#!RZokDQAQ!S3AorYD03T5LV3HwxGse9wQxsBKguv4WJehi5V7RQXA

**Comment by overfl0** [comment]
We're not using gifs in the launcher anymore. We're using zips.

See here for how the indicator looks on the disk right now: https://github.com/overfl0/Bulletproof-Arma-Launcher/blob/next/resources/frontline/images/loader.zip

**Comment by Leondor777** [comment]
[loader_correct.zip](https://github.com/overfl0/Bulletproof-Arma-Launcher/files/850175/loader_correct.zip)
