### ISSUE TITLE
Add Queuing

### ISSUE THREAD

**Issue by mach1muscle351** [overfl0/Bulletproof-Arma-Launcher#224]
Would be nice if possible ;)

**Comment by overfl0** [comment]
Queuing for what?

**Comment by OmanowskiPL** [comment]
bluestacks here,


I believe they're talking about queing for joining the server, ex there would be a queue if the server is full, and it would show you'r place in the queue. of course you could make it so people that donate the money to the server get faster in the queue, but that's the owners decision.

**Comment by OmanowskiPL** [comment]
From my point of view, the whole idea is pretty good.

**Comment by overfl0** [comment]
The problem with such a queue would be that there is actually no way to enforce it. You can't prevent people from running Arma manually and then connecting to the server, circumventing the whole queue mechanism.

What could be done right now (at least more easily) would be to have a notification that says something along the lines of 

```
There are only 5 slots left on this server and you may not be able to connect successfully.
Are you sure you want to connect to it? You can press escape now and select another, less populated, server.

[OK]
```

Pozdrawiam :).

**Comment by mach1muscle351** [comment]
Thought that was obvious. Yes 70/70 players... Gotta keep manually refreshing :/

That last part would be wicked.. Using the launcher as an auto-queuing program wouldn't breach monetization would it? :P you are contributing towards a python program in that case aye?

**Comment by overfl0** [comment]
I'm afraid that this would be much work for nothing.
Not sure how serious you are with that monetization thing but I already can see raised pitchforks if me make ANY type of "priority queue" ;)

**Comment by mach1muscle351** [comment]
Well it's as you said. They can just launch their games and manually override it :P

**Comment by overfl0** [comment]
Sorry, but I don't see it being worth the work and time spent on it.

Maybe as Sighter? :)
