### ISSUE TITLE
Unable to connect to the Teamspeak Server

### ISSUE THREAD

**Issue by Evildog112** [overfl0/Bulletproof-Arma-Launcher#225]
So, pretty much every time I run the game through the launcher I get a popup saying I need to choose a default program to run ts3server. But the only problem is that there is no option to choose TeamSpeak as the default option.
![20170501_013703](https://cloud.githubusercontent.com/assets/28249049/25573358/ac7da1ec-2e12-11e7-88f7-6cfa6bb2d195.jpg)
Clicking anywhere that is not in the box will close it, that is why I had to use my phone to take a picture.
I'm at a loss on what to do next, I reinstalled teamSpeak three times now and still can't get it to work. No clue if it is a windows thing, TeamSpeak thing, or just a problem with the launcher.

**Comment by overfl0** [comment]
This would be a problem with Teamspeak itself, then.
Try to open the files browser and in the location bar, type `ts3server://frontline.frl`.
If you get the same issue, you should try your luck on Teamspeak forum: http://forum.teamspeak.com/
