### ISSUE TITLE
Request: Show terrain name on server overview (Maybe on mouseover?)

### ISSUE THREAD

**Issue by Adanteh** [overfl0/Bulletproof-Arma-Launcher#227]

**Comment by overfl0** [comment]
Is this really needed? I would like to prevent cluttering the interface needlessly.

In other words: is the reason for creating this request the people that don't own APEX (and thus won't be able to play APEX-based maps) or is there a genuine need to know what map is being played right now?

The people that don't own APEX will (in a large majority) not know which custom map uses APEX assets (besides the obvious Tanoa) so I don't think adding that feature will help much in this regard.

**Comment by Adanteh** [comment]
Mouseover please? Just kinda nice to know if you wanna play a certain terrain. For example sometimes I don't care about joining a specific mission

**Comment by overfl0** [comment]
I'll venture a guess that you don't need this feature anymore ;)
