### ISSUE TITLE
Cropped tooltip in mods install window

### ISSUE THREAD

**Issue by MazheM** [overfl0/Bulletproof-Arma-Launcher#235]
Cropped tooltip in mods install window
![Screenshot](https://cloud.githubusercontent.com/assets/5282790/25775260/a948996e-32a9-11e7-9b75-ce3d6a6c115c.png)

**Comment by overfl0** [comment]
Thanks for reporting but this won't be fixed as it's due to the GUI library that we're using.
There is no way to fix this in a reasonable time and I'm not going to be rewriting the launcher to a normal GUI library, like PyQt :(.
