### ISSUE TITLE
Plz Help

### ISSUE THREAD

**Issue by Gamerdfrefdtersa** [overfl0/Bulletproof-Arma-Launcher#236]
How do I get into a server or even play the game, I have the launcher but when I click play I wait and wait and nothing ever happens Plz Help

**Comment by overfl0** [comment]
Try what is written in the troubleshooting guide here:

https://github.com/overfl0/Bulletproof-Arma-Launcher/wiki/Troubleshooting#i-click-play-and-it-does-not-run-arma

If that doesn't help, ask in the Discord channel of your community.
