### ISSUE TITLE
Not launching Arma 3

### ISSUE THREAD

**Issue by Smity22** [overfl0/Bulletproof-Arma-Launcher#246]
Hello,
I have downloaded the mods required for frontlines with no issues and it pops up with the ability to hit play but when i hit play it launches up Teamspeak with my microphone muted and my speakers muted and doesn't launch my Arma 3 however when i go into my processes by pressing cntrl , alt and delete it says that arma3 is running.

Please help.

**Comment by overfl0** [comment]
https://github.com/overfl0/Bulletproof-Arma-Launcher/wiki/Troubleshooting#check-if-arma-is-not-running-in-the-background

`If it is there it means that the launcher launched Arma successfully but Arma itself seems to have a bug. You can try killing the process in the task manager and retrying.`
