### ISSUE TITLE
Error When point to mod location

### ISSUE THREAD

**Issue by Androkiller** [overfl0/Bulletproof-Arma-Launcher#247]
An error occurred in a subprocess:
Build: ad97b4dd1f5fbb0f06288aafa451ea553cb15721
Traceback (most recent call last):
  File "process.py", line 430, in _protected_call
  File "sync\manager_functions.py", line 75, in symlink_mod
  File "sync\torrent_utils.py", line 440, in symlink_mod
  File "sync\torrent_utils.py", line 390, in create_symlink
  File "subprocess.py", line 186, in check_call
CalledProcessError: Command '['cmd', '/c', 'mklink', '/J', 'D:\\Games\\Steam\\steamapps\\common\\Arma 3\\Frontline\\@RHSUSAF', 'D:\\Games\\Steam\\steamapps\\common\\Arma 3\\!Workshop\\@RHSUSAF']' returned non-zero exit status 1

**Comment by overfl0** [comment]
Do you have write rights to `D:\Games\Steam\steamapps\common\Arma 3\Frontline`?
Or maybe you already have an existing directory `D:\Games\Steam\steamapps\common\Arma 3\Frontline\@rhsusaf`?

Try creating the link manually:
start->cmd
`mklink /J "D:\Games\Steam\steamapps\common\Arma 3\Frontline\@rhsusaf" "D:\Games\Steam\steamapps\common\Arma 3\!Workshop\@rhsusaf"`

**Comment by Androkiller** [comment]
so it works when pressing install instead of pointing to the dir in options
