### ISSUE TITLE
Option to Disable Battleye

### ISSUE THREAD

**Issue by JudahHarvey** [overfl0/Bulletproof-Arma-Launcher#252]
Battleye's server routinely disables ACE3 DLLs when either the Battleye server goes down, or for some random reason. Since this launcher is often used by private communities, an option to launch without battleye as these dll blocks are erroneous.

If there could be an easily accessible way to turn off Battleye in the options, and directly launch with command-line it would fix this problem

**Comment by overfl0** [comment]
Hello,

you can already set this option on a per-server basis in metadata.json:
https://github.com/overfl0/Bulletproof-Arma-Launcher/wiki/Mod-management#explanation-of-the-values

Set `"battleye": false` to disable Battleye for a server.
