### ISSUE TITLE
Add -hugepages option

### ISSUE THREAD

**Issue by jonpas** [overfl0/Bulletproof-Arma-Launcher#258]

**Comment by overfl0** [comment]
See those links for how to add it yourself:
https://github.com/overfl0/Bulletproof-Arma-Launcher/commit/8753bb9daa7f4a172189ff16dcc58803051471fd
https://github.com/overfl0/Bulletproof-Arma-Launcher/commit/58ca3de1427c78e8991567f28b1892ad8007170f

**Comment by jonpas** [comment]
Thanks, yes I am planning to add that, just making issues so I don't forget, and in case I don't have time that soon.
