### ISSUE TITLE
Don't show progress indicator when not Updating/Seeding

### ISSUE THREAD

**Issue by Leondor777** [overfl0/Bulletproof-Arma-Launcher#270]
Or show on the last frame (full)

**Comment by overfl0** [comment]
Is this really needed now that https://github.com/overfl0/Bulletproof-Arma-Launcher/issues/268 has been implemented?
Does it really matter that the indicator is moving if the text says "Ready to play"?

**Comment by Leondor777** [comment]
Is it needed? Yes. Is it REALLY needed? No. None of it is a "must have", so up to you.
