### ISSUE TITLE
Kivy doesn't understand UTF-8 text encoding

### ISSUE THREAD

**Issue by REALMWTH** [overfl0/Bulletproof-Arma-Launcher#279]
For some reason changing text: '' fields within kivy files using cyrillic symbols doesn't output correctly.
Probably that's an issue with Window's text encoding using cp-1251 by default. Is there any fix for it?

**Comment by overfl0** [comment]
Make sure you're using the utf-8 encoding because this is probably the
default encoding used by kivy.
niedz., 1 lip 2018, 23:26 użytkownik realmbmc <notifications@github.com>
napisał:

**Comment by overfl0** [comment]
Or this may also be an issue of the default font not supporting those
characters.
Try with another font that you need to put in the same directory as Nexa

niedz., 1 lip 2018, 23:51 użytkownik Łukasz Taczuk <taczuk@gmail.com>
napisał:

**Comment by realmbmc** [comment]
Thanks, I will try to change font and tell you more.
P.S. changed text: '' to text: u'' and now at least symbols are showing up (but in wrong encoding).
If I use string like this: test: 'ФОРУМ' nothing outputs.
