### ISSUE TITLE
Can't download torrent

### ISSUE THREAD

**Issue by JapE1337** [overfl0/Bulletproof-Arma-Launcher#280]
I can't get the launcher to download the mods from the webserver. 
I can easily download the torrent through my browser.

The error: https://gyazo.com/fac5763804fabd1829aae88ae8c1928b

Here's my webserver structure:
```                                
www/                                               
www/metadata.json                                
www/torrents/                                      
www/torrents/@ArmaDilloV4-2018-07-24_1532471252.torrent 
www/mods/                                      
www/mods/@ArmaDilloV4
```
My metadata.json: (http://www.launcher.arma-dillo.dk/metadata.json)
```{
    "protocol": "1.0",
    "refresh": 600,
    "launcher":
    {
        "full_name": "Arma-Dillo Launcher",
        "foldername": "arma-dillo_launcher_autoupdate",
        "torrent-timestamp": "2018-07-24_1532471252",
        "version": "1.8.0"
    },

    "teamspeak": "ts.arma-dillo.dk",

    "servers":
    [
        {
            "name": "[DK] Arma-Dillo.dk Jackson Island",
            "ip": "193.70.81.108",
            "port": "2302",
            "password": "",
            "battleye": true,
            "teamspeak": "ts.arma-dillo.dk"
        }
    ],

    "mods":
    [
        {
            "full_name": "Arma-Dillo Mods",
            "foldername": "@Arma-Dillo",
            "optional": false,
            "torrent-timestamp": "2018-07-24_1532471252"
        }
    ]
} 
```

My launcher configuration:
```
from __future__ import unicode_literals

launcher_name = 'Arma-Dillo Launcher'

default_mods_dir = 'Arma-Dillo'

icon = 'icons/tb.ico'

original_url = 'https://arma-dillo.dk/Arma-Dillo_Launcher.exe'

executable_name = 'Arma-Dillo_Launcher'

forum_url = 'http://arma-dillo.dk/forum'

discord_url = 'ts3server://ts.arma-dillo.dk/?port=9987'

domain = 'launcher.arma-dillo.com'

metadata_path = '/metadata.json'

torrents_path = '/torrents'

troubleshooting_url = 'https://github.com/overfl0/Bulletproof-Arma-Launcher/wiki/Troubleshooting'

bugtracker_url = 'https://github.com/overfl0/Bulletproof-Arma-Launcher/issues'

donate_url = 'https://arma-dillo.dk'

settings_directory = 'Arma-Dillo Launcher'

news_url = 'http://launcher.arma-dillo.dk/news.md'

dominant_color = '#133cdd'

capitalize_status = True
```

**Comment by overfl0** [comment]
Your config says:

```
domain = 'launcher.arma-dillo.com'
metadata_path = '/metadata.json'
```
so the metadata.json should be located here: http://launcher.arma-dillo.com/metadata.json
...and it is located here: http://www.launcher.arma-dillo.dk/metadata.json

Have you changed something lately? I seem to remember that members of the armadillo community have been using the launcher successfully, in the past.

**Comment by JapE1337** [comment]
@overfl0 
Thanks for taking your time, and helping me out here. 

I tried to change to config to this:
```domain = 'www.launcher.arma-dillo.com'```

But it's still not working :/

**Comment by overfl0** [comment]
All your other domains use the `.dk` tld so I think that's the cause of the problem (you're putting the `.com` tld in that part of the config)

**Comment by overfl0** [comment]
You can add a logger line after the line here: https://github.com/overfl0/Bulletproof-Arma-Launcher/blob/next/src/sync/manager_functions.py#L93

After dumping the `url` using the launcher, you can check the url that the launcher is trying to access and check that url if it works for you, manually.
